created: 2026-07-11T22:51:30.260Z
updated: 2026-07-11T22:51:30.260Z
update_count: 1
last_field: description
kind: nested-class
title: custom-handlers
children: []
parentPath:
  - nautilus-runtime
  - strategy-sub
