created: 2026-07-11T22:51:30.370Z
updated: 2026-07-11T22:51:30.370Z
update_count: 1
last_field: description
kind: nested-class
title: order-events
children: []
parentPath:
  - nautilus-runtime
  - strategy-sub
