created: 2026-07-11T22:51:19.508Z
updated: 2026-07-11T22:51:19.670Z
update_count: 2
last_field: description
kind: nested-class
title: strategy-sub
children:
  - custom-handlers
  - data-boundary
  - decision-pipeline
  - event-projection
  - helpers
  - obs-hooks
  - order-events
  - subscriptions
parentPath:
  - nautilus-runtime
