from __future__ import annotations

from typing import Any

PAPER_FILL_REJECTED = "PAPER_FILL_REJECTED"
PAPER_MISSING_ORDERBOOK = "PAPER_MISSING_ORDERBOOK"
PAPER_STALE_ORDERBOOK = "PAPER_STALE_ORDERBOOK"
PAPER_DEPTH_TOO_THIN = "PAPER_DEPTH_TOO_THIN"
PAPER_ENTRY_PRICE_MOVED = "PAPER_ENTRY_PRICE_MOVED"
PAPER_EXTREME_SLIPPAGE = "PAPER_EXTREME_SLIPPAGE"
PAPER_EXPOSURE_LIMIT_REACHED = "PAPER_EXPOSURE_LIMIT_REACHED"
PAPER_WALLET_INSUFFICIENT_CASH = "PAPER_WALLET_INSUFFICIENT_CASH"
PAPER_GTD_EXPIRED = "PAPER_GTD_EXPIRED"
PAPER_MALFORMED_ORDERBOOK = "PAPER_MALFORMED_ORDERBOOK"

_REASON_MAP: dict[str, str] = {
    "MISSING_ORDERBOOK": PAPER_MISSING_ORDERBOOK,
    "MISSING_BEST_ASK": PAPER_MISSING_ORDERBOOK,
    "NO_SNAPSHOT": PAPER_STALE_ORDERBOOK,
    "STALE_ORDERBOOK": PAPER_STALE_ORDERBOOK,
    "HASH_REGRESSION": PAPER_STALE_ORDERBOOK,
    "DELTA_BEFORE_SNAPSHOT": PAPER_STALE_ORDERBOOK,
    "RECONNECT_RESEED_FAILED": PAPER_STALE_ORDERBOOK,
    "TICK_SIZE_CHANGE_RESEED_REQUIRED": PAPER_STALE_ORDERBOOK,
    "BOOK_SEQUENCE_INVALID": PAPER_STALE_ORDERBOOK,
    "INSUFFICIENT_DEPTH": PAPER_DEPTH_TOO_THIN,
    "FOK_INSUFFICIENT_DEPTH": PAPER_DEPTH_TOO_THIN,
    "FAK_NO_LIQUIDITY": PAPER_DEPTH_TOO_THIN,
    "ASK_ABOVE_MAX_ENTRY": PAPER_ENTRY_PRICE_MOVED,
    "SLIPPAGE_EXCEEDS_MAX_ENTRY": PAPER_EXTREME_SLIPPAGE,
    "EXPOSURE_LIMIT_REACHED": PAPER_EXPOSURE_LIMIT_REACHED,
    "MAX_OPEN_POSITIONS_REACHED": PAPER_EXPOSURE_LIMIT_REACHED,
    "WALLET_INSUFFICIENT_CASH": PAPER_WALLET_INSUFFICIENT_CASH,
    "GTD_EXPIRED": PAPER_GTD_EXPIRED,
    "MALFORMED_ORDERBOOK": PAPER_MALFORMED_ORDERBOOK,
}


PaperRejectReason = str | int | float | bool | None


def normalize_paper_reject_reason(reason: PaperRejectReason) -> str:
    if not isinstance(reason, str) or reason == "":
        return PAPER_FILL_REJECTED
    if reason.startswith("PAPER_"):
        return reason
    return _REASON_MAP.get(reason, PAPER_FILL_REJECTED)


def is_rejected_paper_order_payload(
    order: dict[str, Any], metrics: dict[str, Any]
) -> bool:
    status = order.get("status")
    if status == "REJECTED":
        return True
    if status != "CANCELLED":
        return False
    return bool(
        metrics.get("paper_normalized_reason")
        or metrics.get("paper_original_reason")
        or order.get("reject_reason")
    )
